// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module doContrast_doContrast_Pipeline_VITIS_LOOP_18_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inStream_TVALID,
        outStream_TREADY,
        inStream_TDATA,
        inStream_TREADY,
        inStream_TKEEP,
        inStream_TSTRB,
        inStream_TUSER,
        inStream_TLAST,
        inStream_TID,
        inStream_TDEST,
        zext_ln16_1,
        histRange,
        outStream_TDATA,
        outStream_TVALID,
        outStream_TKEEP,
        outStream_TSTRB,
        outStream_TUSER,
        outStream_TLAST,
        outStream_TID,
        outStream_TDEST,
        grp_fu_112_p_din0,
        grp_fu_112_p_dout0,
        grp_fu_112_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   inStream_TVALID;
input   outStream_TREADY;
input  [7:0] inStream_TDATA;
output   inStream_TREADY;
input  [0:0] inStream_TKEEP;
input  [0:0] inStream_TSTRB;
input  [1:0] inStream_TUSER;
input  [0:0] inStream_TLAST;
input  [4:0] inStream_TID;
input  [5:0] inStream_TDEST;
input  [7:0] zext_ln16_1;
input  [31:0] histRange;
output  [7:0] outStream_TDATA;
output   outStream_TVALID;
output  [0:0] outStream_TKEEP;
output  [0:0] outStream_TSTRB;
output  [1:0] outStream_TUSER;
output  [0:0] outStream_TLAST;
output  [4:0] outStream_TID;
output  [5:0] outStream_TDEST;
output  [31:0] grp_fu_112_p_din0;
input  [31:0] grp_fu_112_p_dout0;
output   grp_fu_112_p_ce;

reg ap_idle;
reg inStream_TREADY;
reg outStream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln18_fu_183_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
reg    ap_block_state29_pp0_stage0_iter28;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    inStream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    outStream_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_keep_V_reg_372;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter1_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter2_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter3_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter4_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter5_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter6_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter7_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter8_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter9_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter10_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter11_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter12_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter13_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter14_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter15_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter16_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter17_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter18_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter19_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter20_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter21_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter22_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter23_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter24_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter25_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter26_reg;
reg   [0:0] tmp_keep_V_reg_372_pp0_iter27_reg;
reg   [0:0] tmp_strb_V_reg_377;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter1_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter2_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter3_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter4_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter5_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter6_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter7_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter8_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter9_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter10_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter11_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter12_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter13_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter14_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter15_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter16_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter17_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter18_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter19_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter20_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter21_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter22_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter23_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter24_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter25_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter26_reg;
reg   [0:0] tmp_strb_V_reg_377_pp0_iter27_reg;
reg   [1:0] tmp_user_V_reg_382;
reg   [1:0] tmp_user_V_reg_382_pp0_iter1_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter2_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter3_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter4_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter5_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter6_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter7_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter8_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter9_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter10_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter11_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter12_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter13_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter14_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter15_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter16_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter17_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter18_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter19_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter20_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter21_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter22_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter23_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter24_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter25_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter26_reg;
reg   [1:0] tmp_user_V_reg_382_pp0_iter27_reg;
reg   [0:0] tmp_last_V_reg_387;
reg   [0:0] tmp_last_V_reg_387_pp0_iter1_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter2_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter3_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter4_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter5_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter6_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter7_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter8_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter9_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter10_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter11_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter12_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter13_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter14_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter15_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter16_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter17_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter18_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter19_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter20_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter21_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter22_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter23_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter24_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter25_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter26_reg;
reg   [0:0] tmp_last_V_reg_387_pp0_iter27_reg;
reg   [4:0] tmp_id_V_reg_392;
reg   [4:0] tmp_id_V_reg_392_pp0_iter1_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter2_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter3_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter4_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter5_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter6_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter7_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter8_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter9_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter10_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter11_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter12_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter13_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter14_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter15_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter16_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter17_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter18_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter19_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter20_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter21_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter22_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter23_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter24_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter25_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter26_reg;
reg   [4:0] tmp_id_V_reg_392_pp0_iter27_reg;
reg   [5:0] tmp_dest_V_reg_397;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter1_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter2_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter3_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter4_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter5_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter6_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter7_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter8_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter9_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter10_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter11_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter12_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter13_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter14_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter15_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter16_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter17_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter18_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter19_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter20_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter21_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter22_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter23_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter24_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter25_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter26_reg;
reg   [5:0] tmp_dest_V_reg_397_pp0_iter27_reg;
wire   [8:0] sub_ln29_fu_227_p2;
reg   [8:0] sub_ln29_reg_402;
wire  signed [31:0] sext_ln29_fu_238_p1;
reg   [31:0] conv7_reg_412;
wire   [31:0] grp_fu_164_p2;
reg   [31:0] div_reg_417;
reg   [7:0] tmp_2_reg_422;
wire   [22:0] tmp_3_fu_256_p1;
reg   [22:0] tmp_3_reg_428;
reg   [22:0] tmp_3_reg_428_pp0_iter27_reg;
wire   [0:0] isNeg_fu_269_p3;
reg   [0:0] isNeg_reg_433;
wire   [8:0] ush_fu_286_p3;
reg   [8:0] ush_reg_438;
reg   [16:0] idxPixel_fu_100;
wire   [16:0] idxPixel_2_fu_189_p2;
wire    ap_loop_init;
reg   [16:0] ap_sig_allocacmp_idxPixel_1;
reg    ap_block_pp0_stage0_01001;
wire   [8:0] zext_ln29_fu_223_p1;
wire   [8:0] zext_ln16_1_cast_fu_171_p1;
wire   [31:0] grp_fu_159_p2;
wire   [31:0] data_V_fu_242_p1;
wire   [8:0] zext_ln344_fu_260_p1;
wire   [8:0] add_ln344_fu_263_p2;
wire   [7:0] sub_ln1364_fu_277_p2;
wire  signed [8:0] sext_ln1364_fu_282_p1;
wire   [24:0] mantissa_fu_294_p4;
wire  signed [31:0] sext_ln1340_fu_307_p1;
wire   [54:0] zext_ln68_fu_303_p1;
wire   [54:0] zext_ln1340_fu_310_p1;
wire   [54:0] r_V_fu_314_p2;
wire   [0:0] tmp_fu_326_p3;
wire   [54:0] r_V_1_fu_320_p2;
wire   [7:0] zext_ln671_fu_334_p1;
wire   [7:0] tmp_1_fu_338_p4;
reg    grp_fu_159_ce;
reg    grp_fu_164_ce;
reg    grp_fu_168_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_done_reg = 1'b0;
end

doContrast_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(div_reg_417),
    .din1(32'd1132396544),
    .ce(grp_fu_159_ce),
    .dout(grp_fu_159_p2)
);

doContrast_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv7_reg_412),
    .din1(histRange),
    .ce(grp_fu_164_ce),
    .dout(grp_fu_164_p2)
);

doContrast_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter27_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_start_int == 1'b1) & (icmp_ln18_fu_183_p2 == 1'd0))) begin
            idxPixel_fu_100 <= idxPixel_2_fu_189_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            idxPixel_fu_100 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        conv7_reg_412 <= grp_fu_112_p_dout0;
        div_reg_417 <= grp_fu_164_p2;
        isNeg_reg_433 <= add_ln344_fu_263_p2[32'd8];
        tmp_2_reg_422 <= {{data_V_fu_242_p1[30:23]}};
        tmp_3_reg_428 <= tmp_3_fu_256_p1;
        tmp_3_reg_428_pp0_iter27_reg <= tmp_3_reg_428;
        tmp_dest_V_reg_397_pp0_iter10_reg <= tmp_dest_V_reg_397_pp0_iter9_reg;
        tmp_dest_V_reg_397_pp0_iter11_reg <= tmp_dest_V_reg_397_pp0_iter10_reg;
        tmp_dest_V_reg_397_pp0_iter12_reg <= tmp_dest_V_reg_397_pp0_iter11_reg;
        tmp_dest_V_reg_397_pp0_iter13_reg <= tmp_dest_V_reg_397_pp0_iter12_reg;
        tmp_dest_V_reg_397_pp0_iter14_reg <= tmp_dest_V_reg_397_pp0_iter13_reg;
        tmp_dest_V_reg_397_pp0_iter15_reg <= tmp_dest_V_reg_397_pp0_iter14_reg;
        tmp_dest_V_reg_397_pp0_iter16_reg <= tmp_dest_V_reg_397_pp0_iter15_reg;
        tmp_dest_V_reg_397_pp0_iter17_reg <= tmp_dest_V_reg_397_pp0_iter16_reg;
        tmp_dest_V_reg_397_pp0_iter18_reg <= tmp_dest_V_reg_397_pp0_iter17_reg;
        tmp_dest_V_reg_397_pp0_iter19_reg <= tmp_dest_V_reg_397_pp0_iter18_reg;
        tmp_dest_V_reg_397_pp0_iter20_reg <= tmp_dest_V_reg_397_pp0_iter19_reg;
        tmp_dest_V_reg_397_pp0_iter21_reg <= tmp_dest_V_reg_397_pp0_iter20_reg;
        tmp_dest_V_reg_397_pp0_iter22_reg <= tmp_dest_V_reg_397_pp0_iter21_reg;
        tmp_dest_V_reg_397_pp0_iter23_reg <= tmp_dest_V_reg_397_pp0_iter22_reg;
        tmp_dest_V_reg_397_pp0_iter24_reg <= tmp_dest_V_reg_397_pp0_iter23_reg;
        tmp_dest_V_reg_397_pp0_iter25_reg <= tmp_dest_V_reg_397_pp0_iter24_reg;
        tmp_dest_V_reg_397_pp0_iter26_reg <= tmp_dest_V_reg_397_pp0_iter25_reg;
        tmp_dest_V_reg_397_pp0_iter27_reg <= tmp_dest_V_reg_397_pp0_iter26_reg;
        tmp_dest_V_reg_397_pp0_iter2_reg <= tmp_dest_V_reg_397_pp0_iter1_reg;
        tmp_dest_V_reg_397_pp0_iter3_reg <= tmp_dest_V_reg_397_pp0_iter2_reg;
        tmp_dest_V_reg_397_pp0_iter4_reg <= tmp_dest_V_reg_397_pp0_iter3_reg;
        tmp_dest_V_reg_397_pp0_iter5_reg <= tmp_dest_V_reg_397_pp0_iter4_reg;
        tmp_dest_V_reg_397_pp0_iter6_reg <= tmp_dest_V_reg_397_pp0_iter5_reg;
        tmp_dest_V_reg_397_pp0_iter7_reg <= tmp_dest_V_reg_397_pp0_iter6_reg;
        tmp_dest_V_reg_397_pp0_iter8_reg <= tmp_dest_V_reg_397_pp0_iter7_reg;
        tmp_dest_V_reg_397_pp0_iter9_reg <= tmp_dest_V_reg_397_pp0_iter8_reg;
        tmp_id_V_reg_392_pp0_iter10_reg <= tmp_id_V_reg_392_pp0_iter9_reg;
        tmp_id_V_reg_392_pp0_iter11_reg <= tmp_id_V_reg_392_pp0_iter10_reg;
        tmp_id_V_reg_392_pp0_iter12_reg <= tmp_id_V_reg_392_pp0_iter11_reg;
        tmp_id_V_reg_392_pp0_iter13_reg <= tmp_id_V_reg_392_pp0_iter12_reg;
        tmp_id_V_reg_392_pp0_iter14_reg <= tmp_id_V_reg_392_pp0_iter13_reg;
        tmp_id_V_reg_392_pp0_iter15_reg <= tmp_id_V_reg_392_pp0_iter14_reg;
        tmp_id_V_reg_392_pp0_iter16_reg <= tmp_id_V_reg_392_pp0_iter15_reg;
        tmp_id_V_reg_392_pp0_iter17_reg <= tmp_id_V_reg_392_pp0_iter16_reg;
        tmp_id_V_reg_392_pp0_iter18_reg <= tmp_id_V_reg_392_pp0_iter17_reg;
        tmp_id_V_reg_392_pp0_iter19_reg <= tmp_id_V_reg_392_pp0_iter18_reg;
        tmp_id_V_reg_392_pp0_iter20_reg <= tmp_id_V_reg_392_pp0_iter19_reg;
        tmp_id_V_reg_392_pp0_iter21_reg <= tmp_id_V_reg_392_pp0_iter20_reg;
        tmp_id_V_reg_392_pp0_iter22_reg <= tmp_id_V_reg_392_pp0_iter21_reg;
        tmp_id_V_reg_392_pp0_iter23_reg <= tmp_id_V_reg_392_pp0_iter22_reg;
        tmp_id_V_reg_392_pp0_iter24_reg <= tmp_id_V_reg_392_pp0_iter23_reg;
        tmp_id_V_reg_392_pp0_iter25_reg <= tmp_id_V_reg_392_pp0_iter24_reg;
        tmp_id_V_reg_392_pp0_iter26_reg <= tmp_id_V_reg_392_pp0_iter25_reg;
        tmp_id_V_reg_392_pp0_iter27_reg <= tmp_id_V_reg_392_pp0_iter26_reg;
        tmp_id_V_reg_392_pp0_iter2_reg <= tmp_id_V_reg_392_pp0_iter1_reg;
        tmp_id_V_reg_392_pp0_iter3_reg <= tmp_id_V_reg_392_pp0_iter2_reg;
        tmp_id_V_reg_392_pp0_iter4_reg <= tmp_id_V_reg_392_pp0_iter3_reg;
        tmp_id_V_reg_392_pp0_iter5_reg <= tmp_id_V_reg_392_pp0_iter4_reg;
        tmp_id_V_reg_392_pp0_iter6_reg <= tmp_id_V_reg_392_pp0_iter5_reg;
        tmp_id_V_reg_392_pp0_iter7_reg <= tmp_id_V_reg_392_pp0_iter6_reg;
        tmp_id_V_reg_392_pp0_iter8_reg <= tmp_id_V_reg_392_pp0_iter7_reg;
        tmp_id_V_reg_392_pp0_iter9_reg <= tmp_id_V_reg_392_pp0_iter8_reg;
        tmp_keep_V_reg_372_pp0_iter10_reg <= tmp_keep_V_reg_372_pp0_iter9_reg;
        tmp_keep_V_reg_372_pp0_iter11_reg <= tmp_keep_V_reg_372_pp0_iter10_reg;
        tmp_keep_V_reg_372_pp0_iter12_reg <= tmp_keep_V_reg_372_pp0_iter11_reg;
        tmp_keep_V_reg_372_pp0_iter13_reg <= tmp_keep_V_reg_372_pp0_iter12_reg;
        tmp_keep_V_reg_372_pp0_iter14_reg <= tmp_keep_V_reg_372_pp0_iter13_reg;
        tmp_keep_V_reg_372_pp0_iter15_reg <= tmp_keep_V_reg_372_pp0_iter14_reg;
        tmp_keep_V_reg_372_pp0_iter16_reg <= tmp_keep_V_reg_372_pp0_iter15_reg;
        tmp_keep_V_reg_372_pp0_iter17_reg <= tmp_keep_V_reg_372_pp0_iter16_reg;
        tmp_keep_V_reg_372_pp0_iter18_reg <= tmp_keep_V_reg_372_pp0_iter17_reg;
        tmp_keep_V_reg_372_pp0_iter19_reg <= tmp_keep_V_reg_372_pp0_iter18_reg;
        tmp_keep_V_reg_372_pp0_iter20_reg <= tmp_keep_V_reg_372_pp0_iter19_reg;
        tmp_keep_V_reg_372_pp0_iter21_reg <= tmp_keep_V_reg_372_pp0_iter20_reg;
        tmp_keep_V_reg_372_pp0_iter22_reg <= tmp_keep_V_reg_372_pp0_iter21_reg;
        tmp_keep_V_reg_372_pp0_iter23_reg <= tmp_keep_V_reg_372_pp0_iter22_reg;
        tmp_keep_V_reg_372_pp0_iter24_reg <= tmp_keep_V_reg_372_pp0_iter23_reg;
        tmp_keep_V_reg_372_pp0_iter25_reg <= tmp_keep_V_reg_372_pp0_iter24_reg;
        tmp_keep_V_reg_372_pp0_iter26_reg <= tmp_keep_V_reg_372_pp0_iter25_reg;
        tmp_keep_V_reg_372_pp0_iter27_reg <= tmp_keep_V_reg_372_pp0_iter26_reg;
        tmp_keep_V_reg_372_pp0_iter2_reg <= tmp_keep_V_reg_372_pp0_iter1_reg;
        tmp_keep_V_reg_372_pp0_iter3_reg <= tmp_keep_V_reg_372_pp0_iter2_reg;
        tmp_keep_V_reg_372_pp0_iter4_reg <= tmp_keep_V_reg_372_pp0_iter3_reg;
        tmp_keep_V_reg_372_pp0_iter5_reg <= tmp_keep_V_reg_372_pp0_iter4_reg;
        tmp_keep_V_reg_372_pp0_iter6_reg <= tmp_keep_V_reg_372_pp0_iter5_reg;
        tmp_keep_V_reg_372_pp0_iter7_reg <= tmp_keep_V_reg_372_pp0_iter6_reg;
        tmp_keep_V_reg_372_pp0_iter8_reg <= tmp_keep_V_reg_372_pp0_iter7_reg;
        tmp_keep_V_reg_372_pp0_iter9_reg <= tmp_keep_V_reg_372_pp0_iter8_reg;
        tmp_last_V_reg_387_pp0_iter10_reg <= tmp_last_V_reg_387_pp0_iter9_reg;
        tmp_last_V_reg_387_pp0_iter11_reg <= tmp_last_V_reg_387_pp0_iter10_reg;
        tmp_last_V_reg_387_pp0_iter12_reg <= tmp_last_V_reg_387_pp0_iter11_reg;
        tmp_last_V_reg_387_pp0_iter13_reg <= tmp_last_V_reg_387_pp0_iter12_reg;
        tmp_last_V_reg_387_pp0_iter14_reg <= tmp_last_V_reg_387_pp0_iter13_reg;
        tmp_last_V_reg_387_pp0_iter15_reg <= tmp_last_V_reg_387_pp0_iter14_reg;
        tmp_last_V_reg_387_pp0_iter16_reg <= tmp_last_V_reg_387_pp0_iter15_reg;
        tmp_last_V_reg_387_pp0_iter17_reg <= tmp_last_V_reg_387_pp0_iter16_reg;
        tmp_last_V_reg_387_pp0_iter18_reg <= tmp_last_V_reg_387_pp0_iter17_reg;
        tmp_last_V_reg_387_pp0_iter19_reg <= tmp_last_V_reg_387_pp0_iter18_reg;
        tmp_last_V_reg_387_pp0_iter20_reg <= tmp_last_V_reg_387_pp0_iter19_reg;
        tmp_last_V_reg_387_pp0_iter21_reg <= tmp_last_V_reg_387_pp0_iter20_reg;
        tmp_last_V_reg_387_pp0_iter22_reg <= tmp_last_V_reg_387_pp0_iter21_reg;
        tmp_last_V_reg_387_pp0_iter23_reg <= tmp_last_V_reg_387_pp0_iter22_reg;
        tmp_last_V_reg_387_pp0_iter24_reg <= tmp_last_V_reg_387_pp0_iter23_reg;
        tmp_last_V_reg_387_pp0_iter25_reg <= tmp_last_V_reg_387_pp0_iter24_reg;
        tmp_last_V_reg_387_pp0_iter26_reg <= tmp_last_V_reg_387_pp0_iter25_reg;
        tmp_last_V_reg_387_pp0_iter27_reg <= tmp_last_V_reg_387_pp0_iter26_reg;
        tmp_last_V_reg_387_pp0_iter2_reg <= tmp_last_V_reg_387_pp0_iter1_reg;
        tmp_last_V_reg_387_pp0_iter3_reg <= tmp_last_V_reg_387_pp0_iter2_reg;
        tmp_last_V_reg_387_pp0_iter4_reg <= tmp_last_V_reg_387_pp0_iter3_reg;
        tmp_last_V_reg_387_pp0_iter5_reg <= tmp_last_V_reg_387_pp0_iter4_reg;
        tmp_last_V_reg_387_pp0_iter6_reg <= tmp_last_V_reg_387_pp0_iter5_reg;
        tmp_last_V_reg_387_pp0_iter7_reg <= tmp_last_V_reg_387_pp0_iter6_reg;
        tmp_last_V_reg_387_pp0_iter8_reg <= tmp_last_V_reg_387_pp0_iter7_reg;
        tmp_last_V_reg_387_pp0_iter9_reg <= tmp_last_V_reg_387_pp0_iter8_reg;
        tmp_strb_V_reg_377_pp0_iter10_reg <= tmp_strb_V_reg_377_pp0_iter9_reg;
        tmp_strb_V_reg_377_pp0_iter11_reg <= tmp_strb_V_reg_377_pp0_iter10_reg;
        tmp_strb_V_reg_377_pp0_iter12_reg <= tmp_strb_V_reg_377_pp0_iter11_reg;
        tmp_strb_V_reg_377_pp0_iter13_reg <= tmp_strb_V_reg_377_pp0_iter12_reg;
        tmp_strb_V_reg_377_pp0_iter14_reg <= tmp_strb_V_reg_377_pp0_iter13_reg;
        tmp_strb_V_reg_377_pp0_iter15_reg <= tmp_strb_V_reg_377_pp0_iter14_reg;
        tmp_strb_V_reg_377_pp0_iter16_reg <= tmp_strb_V_reg_377_pp0_iter15_reg;
        tmp_strb_V_reg_377_pp0_iter17_reg <= tmp_strb_V_reg_377_pp0_iter16_reg;
        tmp_strb_V_reg_377_pp0_iter18_reg <= tmp_strb_V_reg_377_pp0_iter17_reg;
        tmp_strb_V_reg_377_pp0_iter19_reg <= tmp_strb_V_reg_377_pp0_iter18_reg;
        tmp_strb_V_reg_377_pp0_iter20_reg <= tmp_strb_V_reg_377_pp0_iter19_reg;
        tmp_strb_V_reg_377_pp0_iter21_reg <= tmp_strb_V_reg_377_pp0_iter20_reg;
        tmp_strb_V_reg_377_pp0_iter22_reg <= tmp_strb_V_reg_377_pp0_iter21_reg;
        tmp_strb_V_reg_377_pp0_iter23_reg <= tmp_strb_V_reg_377_pp0_iter22_reg;
        tmp_strb_V_reg_377_pp0_iter24_reg <= tmp_strb_V_reg_377_pp0_iter23_reg;
        tmp_strb_V_reg_377_pp0_iter25_reg <= tmp_strb_V_reg_377_pp0_iter24_reg;
        tmp_strb_V_reg_377_pp0_iter26_reg <= tmp_strb_V_reg_377_pp0_iter25_reg;
        tmp_strb_V_reg_377_pp0_iter27_reg <= tmp_strb_V_reg_377_pp0_iter26_reg;
        tmp_strb_V_reg_377_pp0_iter2_reg <= tmp_strb_V_reg_377_pp0_iter1_reg;
        tmp_strb_V_reg_377_pp0_iter3_reg <= tmp_strb_V_reg_377_pp0_iter2_reg;
        tmp_strb_V_reg_377_pp0_iter4_reg <= tmp_strb_V_reg_377_pp0_iter3_reg;
        tmp_strb_V_reg_377_pp0_iter5_reg <= tmp_strb_V_reg_377_pp0_iter4_reg;
        tmp_strb_V_reg_377_pp0_iter6_reg <= tmp_strb_V_reg_377_pp0_iter5_reg;
        tmp_strb_V_reg_377_pp0_iter7_reg <= tmp_strb_V_reg_377_pp0_iter6_reg;
        tmp_strb_V_reg_377_pp0_iter8_reg <= tmp_strb_V_reg_377_pp0_iter7_reg;
        tmp_strb_V_reg_377_pp0_iter9_reg <= tmp_strb_V_reg_377_pp0_iter8_reg;
        tmp_user_V_reg_382_pp0_iter10_reg <= tmp_user_V_reg_382_pp0_iter9_reg;
        tmp_user_V_reg_382_pp0_iter11_reg <= tmp_user_V_reg_382_pp0_iter10_reg;
        tmp_user_V_reg_382_pp0_iter12_reg <= tmp_user_V_reg_382_pp0_iter11_reg;
        tmp_user_V_reg_382_pp0_iter13_reg <= tmp_user_V_reg_382_pp0_iter12_reg;
        tmp_user_V_reg_382_pp0_iter14_reg <= tmp_user_V_reg_382_pp0_iter13_reg;
        tmp_user_V_reg_382_pp0_iter15_reg <= tmp_user_V_reg_382_pp0_iter14_reg;
        tmp_user_V_reg_382_pp0_iter16_reg <= tmp_user_V_reg_382_pp0_iter15_reg;
        tmp_user_V_reg_382_pp0_iter17_reg <= tmp_user_V_reg_382_pp0_iter16_reg;
        tmp_user_V_reg_382_pp0_iter18_reg <= tmp_user_V_reg_382_pp0_iter17_reg;
        tmp_user_V_reg_382_pp0_iter19_reg <= tmp_user_V_reg_382_pp0_iter18_reg;
        tmp_user_V_reg_382_pp0_iter20_reg <= tmp_user_V_reg_382_pp0_iter19_reg;
        tmp_user_V_reg_382_pp0_iter21_reg <= tmp_user_V_reg_382_pp0_iter20_reg;
        tmp_user_V_reg_382_pp0_iter22_reg <= tmp_user_V_reg_382_pp0_iter21_reg;
        tmp_user_V_reg_382_pp0_iter23_reg <= tmp_user_V_reg_382_pp0_iter22_reg;
        tmp_user_V_reg_382_pp0_iter24_reg <= tmp_user_V_reg_382_pp0_iter23_reg;
        tmp_user_V_reg_382_pp0_iter25_reg <= tmp_user_V_reg_382_pp0_iter24_reg;
        tmp_user_V_reg_382_pp0_iter26_reg <= tmp_user_V_reg_382_pp0_iter25_reg;
        tmp_user_V_reg_382_pp0_iter27_reg <= tmp_user_V_reg_382_pp0_iter26_reg;
        tmp_user_V_reg_382_pp0_iter2_reg <= tmp_user_V_reg_382_pp0_iter1_reg;
        tmp_user_V_reg_382_pp0_iter3_reg <= tmp_user_V_reg_382_pp0_iter2_reg;
        tmp_user_V_reg_382_pp0_iter4_reg <= tmp_user_V_reg_382_pp0_iter3_reg;
        tmp_user_V_reg_382_pp0_iter5_reg <= tmp_user_V_reg_382_pp0_iter4_reg;
        tmp_user_V_reg_382_pp0_iter6_reg <= tmp_user_V_reg_382_pp0_iter5_reg;
        tmp_user_V_reg_382_pp0_iter7_reg <= tmp_user_V_reg_382_pp0_iter6_reg;
        tmp_user_V_reg_382_pp0_iter8_reg <= tmp_user_V_reg_382_pp0_iter7_reg;
        tmp_user_V_reg_382_pp0_iter9_reg <= tmp_user_V_reg_382_pp0_iter8_reg;
        ush_reg_438 <= ush_fu_286_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_dest_V_reg_397_pp0_iter1_reg <= tmp_dest_V_reg_397;
        tmp_id_V_reg_392_pp0_iter1_reg <= tmp_id_V_reg_392;
        tmp_keep_V_reg_372_pp0_iter1_reg <= tmp_keep_V_reg_372;
        tmp_last_V_reg_387_pp0_iter1_reg <= tmp_last_V_reg_387;
        tmp_strb_V_reg_377_pp0_iter1_reg <= tmp_strb_V_reg_377;
        tmp_user_V_reg_382_pp0_iter1_reg <= tmp_user_V_reg_382;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln18_fu_183_p2 == 1'd0))) begin
        sub_ln29_reg_402 <= sub_ln29_fu_227_p2;
        tmp_dest_V_reg_397 <= inStream_TDEST;
        tmp_id_V_reg_392 <= inStream_TID;
        tmp_keep_V_reg_372 <= inStream_TKEEP;
        tmp_last_V_reg_387 <= inStream_TLAST;
        tmp_strb_V_reg_377 <= inStream_TSTRB;
        tmp_user_V_reg_382 <= inStream_TUSER;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln18_fu_183_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter27_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_idxPixel_1 = 17'd0;
    end else begin
        ap_sig_allocacmp_idxPixel_1 = idxPixel_fu_100;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_159_ce = 1'b1;
    end else begin
        grp_fu_159_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_164_ce = 1'b1;
    end else begin
        grp_fu_164_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_168_ce = 1'b1;
    end else begin
        grp_fu_168_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln18_fu_183_p2 == 1'd0))) begin
        inStream_TDATA_blk_n = inStream_TVALID;
    end else begin
        inStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln18_fu_183_p2 == 1'd0))) begin
        inStream_TREADY = 1'b1;
    end else begin
        inStream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter28 == 1'b1))) begin
        outStream_TDATA_blk_n = outStream_TREADY;
    end else begin
        outStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter28 == 1'b1))) begin
        outStream_TVALID = 1'b1;
    end else begin
        outStream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln344_fu_263_p2 = ($signed(zext_ln344_fu_260_p1) + $signed(9'd385));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((outStream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b1)) | ((ap_start_int == 1'b1) & (icmp_ln18_fu_183_p2 == 1'd0) & (inStream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((outStream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b1)) | ((ap_start_int == 1'b1) & (icmp_ln18_fu_183_p2 == 1'd0) & (inStream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((outStream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b1)) | ((ap_start_int == 1'b1) & (icmp_ln18_fu_183_p2 == 1'd0) & (inStream_TVALID == 1'b0)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln18_fu_183_p2 == 1'd0) & (inStream_TVALID == 1'b0));
end

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state29_pp0_stage0_iter28 = (outStream_TREADY == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign data_V_fu_242_p1 = grp_fu_159_p2;

assign grp_fu_112_p_ce = grp_fu_168_ce;

assign grp_fu_112_p_din0 = sext_ln29_fu_238_p1;

assign icmp_ln18_fu_183_p2 = ((ap_sig_allocacmp_idxPixel_1 == 17'd76800) ? 1'b1 : 1'b0);

assign idxPixel_2_fu_189_p2 = (ap_sig_allocacmp_idxPixel_1 + 17'd1);

assign isNeg_fu_269_p3 = add_ln344_fu_263_p2[32'd8];

assign mantissa_fu_294_p4 = {{{{1'd1}, {tmp_3_reg_428_pp0_iter27_reg}}}, {1'd0}};

assign outStream_TDATA = ((isNeg_reg_433[0:0] == 1'b1) ? zext_ln671_fu_334_p1 : tmp_1_fu_338_p4);

assign outStream_TDEST = tmp_dest_V_reg_397_pp0_iter27_reg;

assign outStream_TID = tmp_id_V_reg_392_pp0_iter27_reg;

assign outStream_TKEEP = tmp_keep_V_reg_372_pp0_iter27_reg;

assign outStream_TLAST = tmp_last_V_reg_387_pp0_iter27_reg;

assign outStream_TSTRB = tmp_strb_V_reg_377_pp0_iter27_reg;

assign outStream_TUSER = tmp_user_V_reg_382_pp0_iter27_reg;

assign r_V_1_fu_320_p2 = zext_ln68_fu_303_p1 << zext_ln1340_fu_310_p1;

assign r_V_fu_314_p2 = zext_ln68_fu_303_p1 >> zext_ln1340_fu_310_p1;

assign sext_ln1340_fu_307_p1 = $signed(ush_reg_438);

assign sext_ln1364_fu_282_p1 = $signed(sub_ln1364_fu_277_p2);

assign sext_ln29_fu_238_p1 = $signed(sub_ln29_reg_402);

assign sub_ln1364_fu_277_p2 = (8'd127 - tmp_2_reg_422);

assign sub_ln29_fu_227_p2 = (zext_ln29_fu_223_p1 - zext_ln16_1_cast_fu_171_p1);

assign tmp_1_fu_338_p4 = {{r_V_1_fu_320_p2[31:24]}};

assign tmp_3_fu_256_p1 = data_V_fu_242_p1[22:0];

assign tmp_fu_326_p3 = r_V_fu_314_p2[32'd24];

assign ush_fu_286_p3 = ((isNeg_fu_269_p3[0:0] == 1'b1) ? sext_ln1364_fu_282_p1 : add_ln344_fu_263_p2);

assign zext_ln1340_fu_310_p1 = $unsigned(sext_ln1340_fu_307_p1);

assign zext_ln16_1_cast_fu_171_p1 = zext_ln16_1;

assign zext_ln29_fu_223_p1 = inStream_TDATA;

assign zext_ln344_fu_260_p1 = tmp_2_reg_422;

assign zext_ln671_fu_334_p1 = tmp_fu_326_p3;

assign zext_ln68_fu_303_p1 = mantissa_fu_294_p4;

endmodule //doContrast_doContrast_Pipeline_VITIS_LOOP_18_1
