
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdocontrast.h"

/*
* The configuration table for devices
*/

XDocontrast_Config XDocontrast_ConfigTable[XPAR_XDOCONTRAST_NUM_INSTANCES] =
{
	{
		XPAR_DOCONTRAST_0_DEVICE_ID,
		XPAR_DOCONTRAST_0_S_AXI_CTRL_BUS_BASEADDR
	}
};


