-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity doContrast_doContrast_Pipeline_VITIS_LOOP_18_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    inStream_TVALID : IN STD_LOGIC;
    outStream_TREADY : IN STD_LOGIC;
    inStream_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    inStream_TREADY : OUT STD_LOGIC;
    inStream_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    inStream_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    inStream_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    inStream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    inStream_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    inStream_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    zext_ln16_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    histRange : IN STD_LOGIC_VECTOR (31 downto 0);
    outStream_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    outStream_TVALID : OUT STD_LOGIC;
    outStream_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    outStream_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    outStream_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    outStream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    outStream_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    outStream_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0);
    grp_fu_112_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_112_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_112_p_ce : OUT STD_LOGIC );
end;


architecture behav of doContrast_doContrast_Pipeline_VITIS_LOOP_18_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_437F0000 : STD_LOGIC_VECTOR (31 downto 0) := "01000011011111110000000000000000";
    constant ap_const_lv17_12C00 : STD_LOGIC_VECTOR (16 downto 0) := "10010110000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln18_fu_183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_state27_pp0_stage0_iter26 : BOOLEAN;
    signal ap_block_state28_pp0_stage0_iter27 : BOOLEAN;
    signal ap_block_state29_pp0_stage0_iter28 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal inStream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal outStream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_keep_V_reg_372 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_reg_372_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_strb_V_reg_377_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_user_V_reg_382 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter15_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter16_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter17_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter18_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter19_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter20_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter21_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter22_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter23_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter24_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter25_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter26_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_V_reg_382_pp0_iter27_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_last_V_reg_387 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_387_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_V_reg_392 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter7_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter8_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter9_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter10_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter11_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter12_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter13_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter14_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter15_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter16_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter17_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter18_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter19_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter20_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter21_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter22_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter23_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter24_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter25_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter26_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_V_reg_392_pp0_iter27_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_dest_V_reg_397 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter11_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter12_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter13_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter14_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter15_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter16_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter17_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter18_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter19_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter20_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter21_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter22_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter23_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter24_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter25_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter26_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_V_reg_397_pp0_iter27_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln29_fu_227_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln29_reg_402 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln29_fu_238_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_reg_412 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_164_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal div_reg_417 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_reg_422 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_256_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_3_reg_428 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_3_reg_428_pp0_iter27_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal isNeg_fu_269_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_reg_433 : STD_LOGIC_VECTOR (0 downto 0);
    signal ush_fu_286_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ush_reg_438 : STD_LOGIC_VECTOR (8 downto 0);
    signal idxPixel_fu_100 : STD_LOGIC_VECTOR (16 downto 0);
    signal idxPixel_2_fu_189_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_idxPixel_1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln29_fu_223_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln16_1_cast_fu_171_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_159_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_V_fu_242_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln344_fu_260_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln344_fu_263_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1364_fu_277_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1364_fu_282_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mantissa_fu_294_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln1340_fu_307_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln68_fu_303_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal zext_ln1340_fu_310_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal r_V_fu_314_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal tmp_fu_326_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_1_fu_320_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal zext_ln671_fu_334_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_338_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_159_ce : STD_LOGIC;
    signal grp_fu_164_ce : STD_LOGIC;
    signal grp_fu_168_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter27_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component doContrast_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component doContrast_fdiv_32ns_32ns_32_16_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component doContrast_sitofp_32s_32_6_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component doContrast_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fmul_32ns_32ns_32_4_max_dsp_1_U1 : component doContrast_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => div_reg_417,
        din1 => ap_const_lv32_437F0000,
        ce => grp_fu_159_ce,
        dout => grp_fu_159_p2);

    fdiv_32ns_32ns_32_16_no_dsp_1_U2 : component doContrast_fdiv_32ns_32ns_32_16_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 16,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => conv7_reg_412,
        din1 => histRange,
        ce => grp_fu_164_ce,
        dout => grp_fu_164_p2);

    flow_control_loop_pipe_sequential_init_U : component doContrast_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter27_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    idxPixel_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_start_int = ap_const_logic_1) and (icmp_ln18_fu_183_p2 = ap_const_lv1_0))) then 
                    idxPixel_fu_100 <= idxPixel_2_fu_189_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    idxPixel_fu_100 <= ap_const_lv17_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                conv7_reg_412 <= grp_fu_112_p_dout0;
                div_reg_417 <= grp_fu_164_p2;
                isNeg_reg_433 <= add_ln344_fu_263_p2(8 downto 8);
                tmp_2_reg_422 <= data_V_fu_242_p1(30 downto 23);
                tmp_3_reg_428 <= tmp_3_fu_256_p1;
                tmp_3_reg_428_pp0_iter27_reg <= tmp_3_reg_428;
                tmp_dest_V_reg_397_pp0_iter10_reg <= tmp_dest_V_reg_397_pp0_iter9_reg;
                tmp_dest_V_reg_397_pp0_iter11_reg <= tmp_dest_V_reg_397_pp0_iter10_reg;
                tmp_dest_V_reg_397_pp0_iter12_reg <= tmp_dest_V_reg_397_pp0_iter11_reg;
                tmp_dest_V_reg_397_pp0_iter13_reg <= tmp_dest_V_reg_397_pp0_iter12_reg;
                tmp_dest_V_reg_397_pp0_iter14_reg <= tmp_dest_V_reg_397_pp0_iter13_reg;
                tmp_dest_V_reg_397_pp0_iter15_reg <= tmp_dest_V_reg_397_pp0_iter14_reg;
                tmp_dest_V_reg_397_pp0_iter16_reg <= tmp_dest_V_reg_397_pp0_iter15_reg;
                tmp_dest_V_reg_397_pp0_iter17_reg <= tmp_dest_V_reg_397_pp0_iter16_reg;
                tmp_dest_V_reg_397_pp0_iter18_reg <= tmp_dest_V_reg_397_pp0_iter17_reg;
                tmp_dest_V_reg_397_pp0_iter19_reg <= tmp_dest_V_reg_397_pp0_iter18_reg;
                tmp_dest_V_reg_397_pp0_iter20_reg <= tmp_dest_V_reg_397_pp0_iter19_reg;
                tmp_dest_V_reg_397_pp0_iter21_reg <= tmp_dest_V_reg_397_pp0_iter20_reg;
                tmp_dest_V_reg_397_pp0_iter22_reg <= tmp_dest_V_reg_397_pp0_iter21_reg;
                tmp_dest_V_reg_397_pp0_iter23_reg <= tmp_dest_V_reg_397_pp0_iter22_reg;
                tmp_dest_V_reg_397_pp0_iter24_reg <= tmp_dest_V_reg_397_pp0_iter23_reg;
                tmp_dest_V_reg_397_pp0_iter25_reg <= tmp_dest_V_reg_397_pp0_iter24_reg;
                tmp_dest_V_reg_397_pp0_iter26_reg <= tmp_dest_V_reg_397_pp0_iter25_reg;
                tmp_dest_V_reg_397_pp0_iter27_reg <= tmp_dest_V_reg_397_pp0_iter26_reg;
                tmp_dest_V_reg_397_pp0_iter2_reg <= tmp_dest_V_reg_397_pp0_iter1_reg;
                tmp_dest_V_reg_397_pp0_iter3_reg <= tmp_dest_V_reg_397_pp0_iter2_reg;
                tmp_dest_V_reg_397_pp0_iter4_reg <= tmp_dest_V_reg_397_pp0_iter3_reg;
                tmp_dest_V_reg_397_pp0_iter5_reg <= tmp_dest_V_reg_397_pp0_iter4_reg;
                tmp_dest_V_reg_397_pp0_iter6_reg <= tmp_dest_V_reg_397_pp0_iter5_reg;
                tmp_dest_V_reg_397_pp0_iter7_reg <= tmp_dest_V_reg_397_pp0_iter6_reg;
                tmp_dest_V_reg_397_pp0_iter8_reg <= tmp_dest_V_reg_397_pp0_iter7_reg;
                tmp_dest_V_reg_397_pp0_iter9_reg <= tmp_dest_V_reg_397_pp0_iter8_reg;
                tmp_id_V_reg_392_pp0_iter10_reg <= tmp_id_V_reg_392_pp0_iter9_reg;
                tmp_id_V_reg_392_pp0_iter11_reg <= tmp_id_V_reg_392_pp0_iter10_reg;
                tmp_id_V_reg_392_pp0_iter12_reg <= tmp_id_V_reg_392_pp0_iter11_reg;
                tmp_id_V_reg_392_pp0_iter13_reg <= tmp_id_V_reg_392_pp0_iter12_reg;
                tmp_id_V_reg_392_pp0_iter14_reg <= tmp_id_V_reg_392_pp0_iter13_reg;
                tmp_id_V_reg_392_pp0_iter15_reg <= tmp_id_V_reg_392_pp0_iter14_reg;
                tmp_id_V_reg_392_pp0_iter16_reg <= tmp_id_V_reg_392_pp0_iter15_reg;
                tmp_id_V_reg_392_pp0_iter17_reg <= tmp_id_V_reg_392_pp0_iter16_reg;
                tmp_id_V_reg_392_pp0_iter18_reg <= tmp_id_V_reg_392_pp0_iter17_reg;
                tmp_id_V_reg_392_pp0_iter19_reg <= tmp_id_V_reg_392_pp0_iter18_reg;
                tmp_id_V_reg_392_pp0_iter20_reg <= tmp_id_V_reg_392_pp0_iter19_reg;
                tmp_id_V_reg_392_pp0_iter21_reg <= tmp_id_V_reg_392_pp0_iter20_reg;
                tmp_id_V_reg_392_pp0_iter22_reg <= tmp_id_V_reg_392_pp0_iter21_reg;
                tmp_id_V_reg_392_pp0_iter23_reg <= tmp_id_V_reg_392_pp0_iter22_reg;
                tmp_id_V_reg_392_pp0_iter24_reg <= tmp_id_V_reg_392_pp0_iter23_reg;
                tmp_id_V_reg_392_pp0_iter25_reg <= tmp_id_V_reg_392_pp0_iter24_reg;
                tmp_id_V_reg_392_pp0_iter26_reg <= tmp_id_V_reg_392_pp0_iter25_reg;
                tmp_id_V_reg_392_pp0_iter27_reg <= tmp_id_V_reg_392_pp0_iter26_reg;
                tmp_id_V_reg_392_pp0_iter2_reg <= tmp_id_V_reg_392_pp0_iter1_reg;
                tmp_id_V_reg_392_pp0_iter3_reg <= tmp_id_V_reg_392_pp0_iter2_reg;
                tmp_id_V_reg_392_pp0_iter4_reg <= tmp_id_V_reg_392_pp0_iter3_reg;
                tmp_id_V_reg_392_pp0_iter5_reg <= tmp_id_V_reg_392_pp0_iter4_reg;
                tmp_id_V_reg_392_pp0_iter6_reg <= tmp_id_V_reg_392_pp0_iter5_reg;
                tmp_id_V_reg_392_pp0_iter7_reg <= tmp_id_V_reg_392_pp0_iter6_reg;
                tmp_id_V_reg_392_pp0_iter8_reg <= tmp_id_V_reg_392_pp0_iter7_reg;
                tmp_id_V_reg_392_pp0_iter9_reg <= tmp_id_V_reg_392_pp0_iter8_reg;
                tmp_keep_V_reg_372_pp0_iter10_reg <= tmp_keep_V_reg_372_pp0_iter9_reg;
                tmp_keep_V_reg_372_pp0_iter11_reg <= tmp_keep_V_reg_372_pp0_iter10_reg;
                tmp_keep_V_reg_372_pp0_iter12_reg <= tmp_keep_V_reg_372_pp0_iter11_reg;
                tmp_keep_V_reg_372_pp0_iter13_reg <= tmp_keep_V_reg_372_pp0_iter12_reg;
                tmp_keep_V_reg_372_pp0_iter14_reg <= tmp_keep_V_reg_372_pp0_iter13_reg;
                tmp_keep_V_reg_372_pp0_iter15_reg <= tmp_keep_V_reg_372_pp0_iter14_reg;
                tmp_keep_V_reg_372_pp0_iter16_reg <= tmp_keep_V_reg_372_pp0_iter15_reg;
                tmp_keep_V_reg_372_pp0_iter17_reg <= tmp_keep_V_reg_372_pp0_iter16_reg;
                tmp_keep_V_reg_372_pp0_iter18_reg <= tmp_keep_V_reg_372_pp0_iter17_reg;
                tmp_keep_V_reg_372_pp0_iter19_reg <= tmp_keep_V_reg_372_pp0_iter18_reg;
                tmp_keep_V_reg_372_pp0_iter20_reg <= tmp_keep_V_reg_372_pp0_iter19_reg;
                tmp_keep_V_reg_372_pp0_iter21_reg <= tmp_keep_V_reg_372_pp0_iter20_reg;
                tmp_keep_V_reg_372_pp0_iter22_reg <= tmp_keep_V_reg_372_pp0_iter21_reg;
                tmp_keep_V_reg_372_pp0_iter23_reg <= tmp_keep_V_reg_372_pp0_iter22_reg;
                tmp_keep_V_reg_372_pp0_iter24_reg <= tmp_keep_V_reg_372_pp0_iter23_reg;
                tmp_keep_V_reg_372_pp0_iter25_reg <= tmp_keep_V_reg_372_pp0_iter24_reg;
                tmp_keep_V_reg_372_pp0_iter26_reg <= tmp_keep_V_reg_372_pp0_iter25_reg;
                tmp_keep_V_reg_372_pp0_iter27_reg <= tmp_keep_V_reg_372_pp0_iter26_reg;
                tmp_keep_V_reg_372_pp0_iter2_reg <= tmp_keep_V_reg_372_pp0_iter1_reg;
                tmp_keep_V_reg_372_pp0_iter3_reg <= tmp_keep_V_reg_372_pp0_iter2_reg;
                tmp_keep_V_reg_372_pp0_iter4_reg <= tmp_keep_V_reg_372_pp0_iter3_reg;
                tmp_keep_V_reg_372_pp0_iter5_reg <= tmp_keep_V_reg_372_pp0_iter4_reg;
                tmp_keep_V_reg_372_pp0_iter6_reg <= tmp_keep_V_reg_372_pp0_iter5_reg;
                tmp_keep_V_reg_372_pp0_iter7_reg <= tmp_keep_V_reg_372_pp0_iter6_reg;
                tmp_keep_V_reg_372_pp0_iter8_reg <= tmp_keep_V_reg_372_pp0_iter7_reg;
                tmp_keep_V_reg_372_pp0_iter9_reg <= tmp_keep_V_reg_372_pp0_iter8_reg;
                tmp_last_V_reg_387_pp0_iter10_reg <= tmp_last_V_reg_387_pp0_iter9_reg;
                tmp_last_V_reg_387_pp0_iter11_reg <= tmp_last_V_reg_387_pp0_iter10_reg;
                tmp_last_V_reg_387_pp0_iter12_reg <= tmp_last_V_reg_387_pp0_iter11_reg;
                tmp_last_V_reg_387_pp0_iter13_reg <= tmp_last_V_reg_387_pp0_iter12_reg;
                tmp_last_V_reg_387_pp0_iter14_reg <= tmp_last_V_reg_387_pp0_iter13_reg;
                tmp_last_V_reg_387_pp0_iter15_reg <= tmp_last_V_reg_387_pp0_iter14_reg;
                tmp_last_V_reg_387_pp0_iter16_reg <= tmp_last_V_reg_387_pp0_iter15_reg;
                tmp_last_V_reg_387_pp0_iter17_reg <= tmp_last_V_reg_387_pp0_iter16_reg;
                tmp_last_V_reg_387_pp0_iter18_reg <= tmp_last_V_reg_387_pp0_iter17_reg;
                tmp_last_V_reg_387_pp0_iter19_reg <= tmp_last_V_reg_387_pp0_iter18_reg;
                tmp_last_V_reg_387_pp0_iter20_reg <= tmp_last_V_reg_387_pp0_iter19_reg;
                tmp_last_V_reg_387_pp0_iter21_reg <= tmp_last_V_reg_387_pp0_iter20_reg;
                tmp_last_V_reg_387_pp0_iter22_reg <= tmp_last_V_reg_387_pp0_iter21_reg;
                tmp_last_V_reg_387_pp0_iter23_reg <= tmp_last_V_reg_387_pp0_iter22_reg;
                tmp_last_V_reg_387_pp0_iter24_reg <= tmp_last_V_reg_387_pp0_iter23_reg;
                tmp_last_V_reg_387_pp0_iter25_reg <= tmp_last_V_reg_387_pp0_iter24_reg;
                tmp_last_V_reg_387_pp0_iter26_reg <= tmp_last_V_reg_387_pp0_iter25_reg;
                tmp_last_V_reg_387_pp0_iter27_reg <= tmp_last_V_reg_387_pp0_iter26_reg;
                tmp_last_V_reg_387_pp0_iter2_reg <= tmp_last_V_reg_387_pp0_iter1_reg;
                tmp_last_V_reg_387_pp0_iter3_reg <= tmp_last_V_reg_387_pp0_iter2_reg;
                tmp_last_V_reg_387_pp0_iter4_reg <= tmp_last_V_reg_387_pp0_iter3_reg;
                tmp_last_V_reg_387_pp0_iter5_reg <= tmp_last_V_reg_387_pp0_iter4_reg;
                tmp_last_V_reg_387_pp0_iter6_reg <= tmp_last_V_reg_387_pp0_iter5_reg;
                tmp_last_V_reg_387_pp0_iter7_reg <= tmp_last_V_reg_387_pp0_iter6_reg;
                tmp_last_V_reg_387_pp0_iter8_reg <= tmp_last_V_reg_387_pp0_iter7_reg;
                tmp_last_V_reg_387_pp0_iter9_reg <= tmp_last_V_reg_387_pp0_iter8_reg;
                tmp_strb_V_reg_377_pp0_iter10_reg <= tmp_strb_V_reg_377_pp0_iter9_reg;
                tmp_strb_V_reg_377_pp0_iter11_reg <= tmp_strb_V_reg_377_pp0_iter10_reg;
                tmp_strb_V_reg_377_pp0_iter12_reg <= tmp_strb_V_reg_377_pp0_iter11_reg;
                tmp_strb_V_reg_377_pp0_iter13_reg <= tmp_strb_V_reg_377_pp0_iter12_reg;
                tmp_strb_V_reg_377_pp0_iter14_reg <= tmp_strb_V_reg_377_pp0_iter13_reg;
                tmp_strb_V_reg_377_pp0_iter15_reg <= tmp_strb_V_reg_377_pp0_iter14_reg;
                tmp_strb_V_reg_377_pp0_iter16_reg <= tmp_strb_V_reg_377_pp0_iter15_reg;
                tmp_strb_V_reg_377_pp0_iter17_reg <= tmp_strb_V_reg_377_pp0_iter16_reg;
                tmp_strb_V_reg_377_pp0_iter18_reg <= tmp_strb_V_reg_377_pp0_iter17_reg;
                tmp_strb_V_reg_377_pp0_iter19_reg <= tmp_strb_V_reg_377_pp0_iter18_reg;
                tmp_strb_V_reg_377_pp0_iter20_reg <= tmp_strb_V_reg_377_pp0_iter19_reg;
                tmp_strb_V_reg_377_pp0_iter21_reg <= tmp_strb_V_reg_377_pp0_iter20_reg;
                tmp_strb_V_reg_377_pp0_iter22_reg <= tmp_strb_V_reg_377_pp0_iter21_reg;
                tmp_strb_V_reg_377_pp0_iter23_reg <= tmp_strb_V_reg_377_pp0_iter22_reg;
                tmp_strb_V_reg_377_pp0_iter24_reg <= tmp_strb_V_reg_377_pp0_iter23_reg;
                tmp_strb_V_reg_377_pp0_iter25_reg <= tmp_strb_V_reg_377_pp0_iter24_reg;
                tmp_strb_V_reg_377_pp0_iter26_reg <= tmp_strb_V_reg_377_pp0_iter25_reg;
                tmp_strb_V_reg_377_pp0_iter27_reg <= tmp_strb_V_reg_377_pp0_iter26_reg;
                tmp_strb_V_reg_377_pp0_iter2_reg <= tmp_strb_V_reg_377_pp0_iter1_reg;
                tmp_strb_V_reg_377_pp0_iter3_reg <= tmp_strb_V_reg_377_pp0_iter2_reg;
                tmp_strb_V_reg_377_pp0_iter4_reg <= tmp_strb_V_reg_377_pp0_iter3_reg;
                tmp_strb_V_reg_377_pp0_iter5_reg <= tmp_strb_V_reg_377_pp0_iter4_reg;
                tmp_strb_V_reg_377_pp0_iter6_reg <= tmp_strb_V_reg_377_pp0_iter5_reg;
                tmp_strb_V_reg_377_pp0_iter7_reg <= tmp_strb_V_reg_377_pp0_iter6_reg;
                tmp_strb_V_reg_377_pp0_iter8_reg <= tmp_strb_V_reg_377_pp0_iter7_reg;
                tmp_strb_V_reg_377_pp0_iter9_reg <= tmp_strb_V_reg_377_pp0_iter8_reg;
                tmp_user_V_reg_382_pp0_iter10_reg <= tmp_user_V_reg_382_pp0_iter9_reg;
                tmp_user_V_reg_382_pp0_iter11_reg <= tmp_user_V_reg_382_pp0_iter10_reg;
                tmp_user_V_reg_382_pp0_iter12_reg <= tmp_user_V_reg_382_pp0_iter11_reg;
                tmp_user_V_reg_382_pp0_iter13_reg <= tmp_user_V_reg_382_pp0_iter12_reg;
                tmp_user_V_reg_382_pp0_iter14_reg <= tmp_user_V_reg_382_pp0_iter13_reg;
                tmp_user_V_reg_382_pp0_iter15_reg <= tmp_user_V_reg_382_pp0_iter14_reg;
                tmp_user_V_reg_382_pp0_iter16_reg <= tmp_user_V_reg_382_pp0_iter15_reg;
                tmp_user_V_reg_382_pp0_iter17_reg <= tmp_user_V_reg_382_pp0_iter16_reg;
                tmp_user_V_reg_382_pp0_iter18_reg <= tmp_user_V_reg_382_pp0_iter17_reg;
                tmp_user_V_reg_382_pp0_iter19_reg <= tmp_user_V_reg_382_pp0_iter18_reg;
                tmp_user_V_reg_382_pp0_iter20_reg <= tmp_user_V_reg_382_pp0_iter19_reg;
                tmp_user_V_reg_382_pp0_iter21_reg <= tmp_user_V_reg_382_pp0_iter20_reg;
                tmp_user_V_reg_382_pp0_iter22_reg <= tmp_user_V_reg_382_pp0_iter21_reg;
                tmp_user_V_reg_382_pp0_iter23_reg <= tmp_user_V_reg_382_pp0_iter22_reg;
                tmp_user_V_reg_382_pp0_iter24_reg <= tmp_user_V_reg_382_pp0_iter23_reg;
                tmp_user_V_reg_382_pp0_iter25_reg <= tmp_user_V_reg_382_pp0_iter24_reg;
                tmp_user_V_reg_382_pp0_iter26_reg <= tmp_user_V_reg_382_pp0_iter25_reg;
                tmp_user_V_reg_382_pp0_iter27_reg <= tmp_user_V_reg_382_pp0_iter26_reg;
                tmp_user_V_reg_382_pp0_iter2_reg <= tmp_user_V_reg_382_pp0_iter1_reg;
                tmp_user_V_reg_382_pp0_iter3_reg <= tmp_user_V_reg_382_pp0_iter2_reg;
                tmp_user_V_reg_382_pp0_iter4_reg <= tmp_user_V_reg_382_pp0_iter3_reg;
                tmp_user_V_reg_382_pp0_iter5_reg <= tmp_user_V_reg_382_pp0_iter4_reg;
                tmp_user_V_reg_382_pp0_iter6_reg <= tmp_user_V_reg_382_pp0_iter5_reg;
                tmp_user_V_reg_382_pp0_iter7_reg <= tmp_user_V_reg_382_pp0_iter6_reg;
                tmp_user_V_reg_382_pp0_iter8_reg <= tmp_user_V_reg_382_pp0_iter7_reg;
                tmp_user_V_reg_382_pp0_iter9_reg <= tmp_user_V_reg_382_pp0_iter8_reg;
                ush_reg_438 <= ush_fu_286_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                tmp_dest_V_reg_397_pp0_iter1_reg <= tmp_dest_V_reg_397;
                tmp_id_V_reg_392_pp0_iter1_reg <= tmp_id_V_reg_392;
                tmp_keep_V_reg_372_pp0_iter1_reg <= tmp_keep_V_reg_372;
                tmp_last_V_reg_387_pp0_iter1_reg <= tmp_last_V_reg_387;
                tmp_strb_V_reg_377_pp0_iter1_reg <= tmp_strb_V_reg_377;
                tmp_user_V_reg_382_pp0_iter1_reg <= tmp_user_V_reg_382;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln18_fu_183_p2 = ap_const_lv1_0))) then
                sub_ln29_reg_402 <= sub_ln29_fu_227_p2;
                tmp_dest_V_reg_397 <= inStream_TDEST;
                tmp_id_V_reg_392 <= inStream_TID;
                tmp_keep_V_reg_372 <= inStream_TKEEP;
                tmp_last_V_reg_387 <= inStream_TLAST;
                tmp_strb_V_reg_377 <= inStream_TSTRB;
                tmp_user_V_reg_382 <= inStream_TUSER;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln344_fu_263_p2 <= std_logic_vector(unsigned(zext_ln344_fu_260_p1) + unsigned(ap_const_lv9_181));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter28, inStream_TVALID, icmp_ln18_fu_183_p2, outStream_TREADY, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((outStream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (icmp_ln18_fu_183_p2 = ap_const_lv1_0) and (inStream_TVALID = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter28, inStream_TVALID, icmp_ln18_fu_183_p2, outStream_TREADY, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((outStream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (icmp_ln18_fu_183_p2 = ap_const_lv1_0) and (inStream_TVALID = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter28, inStream_TVALID, icmp_ln18_fu_183_p2, outStream_TREADY, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((outStream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (icmp_ln18_fu_183_p2 = ap_const_lv1_0) and (inStream_TVALID = ap_const_logic_0)));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(inStream_TVALID, icmp_ln18_fu_183_p2)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((icmp_ln18_fu_183_p2 = ap_const_lv1_0) and (inStream_TVALID = ap_const_logic_0));
    end process;

        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp0_stage0_iter26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp0_stage0_iter27 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state29_pp0_stage0_iter28_assign_proc : process(outStream_TREADY)
    begin
                ap_block_state29_pp0_stage0_iter28 <= (outStream_TREADY = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln18_fu_183_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln18_fu_183_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter27_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter27_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_idxPixel_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, idxPixel_fu_100, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_idxPixel_1 <= ap_const_lv17_0;
        else 
            ap_sig_allocacmp_idxPixel_1 <= idxPixel_fu_100;
        end if; 
    end process;

    data_V_fu_242_p1 <= grp_fu_159_p2;
    grp_fu_112_p_ce <= grp_fu_168_ce;
    grp_fu_112_p_din0 <= sext_ln29_fu_238_p1;

    grp_fu_159_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_159_ce <= ap_const_logic_1;
        else 
            grp_fu_159_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_164_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_164_ce <= ap_const_logic_1;
        else 
            grp_fu_164_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_168_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_168_ce <= ap_const_logic_1;
        else 
            grp_fu_168_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln18_fu_183_p2 <= "1" when (ap_sig_allocacmp_idxPixel_1 = ap_const_lv17_12C00) else "0";
    idxPixel_2_fu_189_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_idxPixel_1) + unsigned(ap_const_lv17_1));

    inStream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, inStream_TVALID, icmp_ln18_fu_183_p2, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln18_fu_183_p2 = ap_const_lv1_0))) then 
            inStream_TDATA_blk_n <= inStream_TVALID;
        else 
            inStream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    inStream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln18_fu_183_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln18_fu_183_p2 = ap_const_lv1_0))) then 
            inStream_TREADY <= ap_const_logic_1;
        else 
            inStream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    isNeg_fu_269_p3 <= add_ln344_fu_263_p2(8 downto 8);
    mantissa_fu_294_p4 <= ((ap_const_lv1_1 & tmp_3_reg_428_pp0_iter27_reg) & ap_const_lv1_0);
    outStream_TDATA <= 
        zext_ln671_fu_334_p1 when (isNeg_reg_433(0) = '1') else 
        tmp_1_fu_338_p4;

    outStream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter28, outStream_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_1))) then 
            outStream_TDATA_blk_n <= outStream_TREADY;
        else 
            outStream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outStream_TDEST <= tmp_dest_V_reg_397_pp0_iter27_reg;
    outStream_TID <= tmp_id_V_reg_392_pp0_iter27_reg;
    outStream_TKEEP <= tmp_keep_V_reg_372_pp0_iter27_reg;
    outStream_TLAST <= tmp_last_V_reg_387_pp0_iter27_reg;
    outStream_TSTRB <= tmp_strb_V_reg_377_pp0_iter27_reg;
    outStream_TUSER <= tmp_user_V_reg_382_pp0_iter27_reg;

    outStream_TVALID_assign_proc : process(ap_enable_reg_pp0_iter28, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter28 = ap_const_logic_1))) then 
            outStream_TVALID <= ap_const_logic_1;
        else 
            outStream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    r_V_1_fu_320_p2 <= std_logic_vector(shift_left(unsigned(zext_ln68_fu_303_p1),to_integer(unsigned('0' & zext_ln1340_fu_310_p1(31-1 downto 0)))));
    r_V_fu_314_p2 <= std_logic_vector(shift_right(unsigned(zext_ln68_fu_303_p1),to_integer(unsigned('0' & zext_ln1340_fu_310_p1(31-1 downto 0)))));
        sext_ln1340_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_reg_438),32));

        sext_ln1364_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1364_fu_277_p2),9));

        sext_ln29_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln29_reg_402),32));

    sub_ln1364_fu_277_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(tmp_2_reg_422));
    sub_ln29_fu_227_p2 <= std_logic_vector(unsigned(zext_ln29_fu_223_p1) - unsigned(zext_ln16_1_cast_fu_171_p1));
    tmp_1_fu_338_p4 <= r_V_1_fu_320_p2(31 downto 24);
    tmp_3_fu_256_p1 <= data_V_fu_242_p1(23 - 1 downto 0);
    tmp_fu_326_p3 <= r_V_fu_314_p2(24 downto 24);
    ush_fu_286_p3 <= 
        sext_ln1364_fu_282_p1 when (isNeg_fu_269_p3(0) = '1') else 
        add_ln344_fu_263_p2;
    zext_ln1340_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1340_fu_307_p1),55));
    zext_ln16_1_cast_fu_171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln16_1),9));
    zext_ln29_fu_223_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(inStream_TDATA),9));
    zext_ln344_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_422),9));
    zext_ln671_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_326_p3),8));
    zext_ln68_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_294_p4),55));
end behav;
