
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdohist.h"

/*
* The configuration table for devices
*/

XDohist_Config XDohist_ConfigTable[XPAR_XDOHIST_NUM_INSTANCES] =
{
	{
		XPAR_DOHIST_0_DEVICE_ID,
		XPAR_DOHIST_0_S_AXI_CTRL_BUS_BASEADDR
	}
};


